# CHAT PATROL CONFIGURATION | BY JAMPLIFIER
# SUPPORT http://discord.gg/simplestudio

# WORD FILTER
ENABLE-WORD-FILTER: true
BLACKLISTED-WORDS:
  - "badword1"
  - "badword2"

# SPAM FILTER
ENABLE-SPAM-FILTER: true
SPAM-THRESHOLD: 5
SPAM-TIME-WINDOW: 4

# CAPS LOCK FILTER
ENABLE-CAPS-FILTER: true
CAPS-THRESHOLD: 3
CAPS-NOTIFICATION: true

# COMMAND TO EXECUTE FOR PUNISHMENTS
PUNISHMENTS:
  BLACKLISTED-WORDS-COMMAND: "ban {player} You were banned for using inappropriate language!"
  SPAM-COMMAND: "kick {player} You were kicked for spamming!"