name: ChatPatrol
main: com.simplesetupmc.chatpatrol.MainClass
version: 2.0.1
api-version: 1.16
description: A plugin to monitor and control chat using blacklisted words.
folia-supported: true

commands:
  chatpatrol:
    aliases: [cp]
    description: Main command for ChatPatrol.
    usage: "/<command> reload"

permissions:
  chatpatrol.admin:
    description: Allows access to admin commands for ChatPatrol.
    default: op
